/// Subclass of IBSP.CONN.SAML11.CORE.AttributeValue which allows xsi:type attriibute on input
/// 
/// This class is used internally by Cach&eacute;. You should not make direct
/// use of it within your applications. There is no guarantee made about either
/// the behavior or future operation of this class.
Class IBSP.CONN.SAML11.CORE.AttributeStringValue Extends IBSP.CONN.SAML11.CORE.AttributeValue [ System = 4 ]
{

Parameter XMLTYPE = "string";

}
